# This is a minimal but complete settings.yml file for SearXNG in Docker.

server:
  bind_address: "0.0.0.0"
  port: 8888
  base_url: "http://127.0.0.1:8888"
  secret_key: "1a8afd7c3b9a3e3b9e4b7b1b3a5a7b1b" # Replace with a new key

general:
  # This section is required by the application, including the DOI resolver.
  instance_name: "My SearXNG"
  default_doi_resolver: "doi.org"

ui:
  # This section is also required for the UI to load correctly.
  static_path: "static"
  default_theme: "simple"
  default_infobox: "osm"
  default_lang: "en"

# Use a minimal, reliable set of search engines with the correct format.
engines:
  - name: google
    disabled: false
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false

# Explicitly disable security features that can cause issues in this setup.
security:
  bot_detection:
    method: none
  ip_limiter:
    behind_proxy: false
    rules: []
