# Definitive settings.yml for SearXNG in Docker

server:
  bind_address: "0.0.0.0"
  port: 8888
  base_url: "http://127.0.0.1:8888"
  secret_key: "1a8afd7c3b9a3e3b9e4b7b1b3a5a7b1b"

# This key IS REQUIRED by the latest application code.
default_doi_resolver: "doi.org"

general:
  instance_name: "My SearXNG"
  # This provides the valid choices for the preference.
  doi_resolvers:
    "doi.org": "doi.org"

ui:
  default_theme: "simple"
  default_infobox: "osm"
  default_lang: "en"

search:
  # We are NOT locking the doi_resolver preference to avoid the validation bug.
  lock_preferences: []

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false
  - name: bing
    engine: bing
    shortcut: b
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
    disabled: false

security:
  trusted_hosts:
    - "127.0.0.1:8888"
  bot_detection:
    method: none
  ip_limiter:
    behind_proxy: false
    rules: []
