# Definitive settings.yml file for SearXNG in Docker.

server:
  bind_address: "0.0.0.0"
  port: 8888
  base_url: "http://127.0.0.1:8888"
  secret_key: "1a8afd7c3b9a3e3b9e4b7b1b3a5a7b1b" # Replace with a new key

# This key MUST be at the top level, and its value MUST be a simple domain.
default_doi_resolver: "doi.org"

general:
  instance_name: "My SearXNG"
  # This list is ALSO required to define the valid choices for the setting above.
  doi_resolvers:
    "doi.org": "doi.org"

ui:
  default_theme: "simple"
  default_infobox: "osm"
  default_lang: "en"

# Use a minimal, reliable set of search engines.
engines:
  - name: google
    disabled: false
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false

# Explicitly disable security features and trust the internal Host header.
security:
  trusted_hosts:
    - "127.0.0.1:8888"
  bot_detection:
    method: none
  ip_limiter:
    behind_proxy: false
    rules: []
