# Definitive settings.yml file for SearXNG in Docker.

server:
  bind_address: "0.0.0.0"
  port: 8888
  base_url: "http://127.0.0.1:8888"
  secret_key: "1a8afd7c3b9a3e3b9e4b7b1b3a5a7b1b"  # Replace this with a secure random value in production

# Must match one of the keys in the doi_resolvers dictionary below
default_doi_resolver: "https://doi.org"

general:
  instance_name: "My SearXNG"
  # List of allowed DOI resolvers; keys are the URLs to match, values are human-readable names
  doi_resolvers:
    "https://doi.org": "doi.org"

ui:
  default_theme: "simple"
  default_infobox: "osm"
  default_lang: "en"

engines:
  - name: google
    disabled: false
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false

# Disable all protection mechanisms for simplicity in internal container use
security:
  trusted_hosts:
    - "127.0.0.1:8888"
  bot_detection:
    method: none
  ip_limiter:
    behind_proxy: false
    rules: []
